spring:    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  
  mail:
    host: smtp.gmail.com
    port: 587
    username: kashad075@gmail.com
    password: yohghzvmbngaffnu
    properties.mail.smtp.auth: true
    properties.mail.smtp.starttls.enable: true
    
  datasource:
     url: jdbc:mysql://localhost:3306/major-project?createDatabaseIfNotExist=true
     username: root
     password: 1234
     driver-class-name: com.mysql.cj.jdbc.Driver
     
  boot:
    admin:
      client:
        url: http://localhost:1111/
        
server:
  port: 4444

  
management:
  endpoints:
    web:
      exposure:
        include: '*'
 


