
spring:
  boot:
    admin:
      client:
        url: http://localhost:1111/
  datasource:
    username: root
    password: 1234
    url: jdbc:mysql://localhost:3306/major-project

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    
management:
  endpoints:
    web:
      exposure:
        include: '*'

server:
 port: 8082

product-service:
 messages:
  categoryAdded: Category Added Successfully
  categoryAddErr: Failed to Add Category
  categoryUpdate: Category Updated Successfully
  categoryUpdateErr: Failed to update category
  categoryFetch: All Categories fetched successfully
  categoryFetchErr: Failed to fetch all categories
  categorySelect: Category Retrieved Successfully
  categorySelectErr: Failed to retrieve category
  categoryDelete: Category deleted successfully
  categoryDeleteErr: Failed to delete category
  productAdded: Product Added Successfully
  productAddErr: Failed to Add Product
  productUpdate: Product Updated Successfully
  productUpdateErr: Failed to update Product
  productFetch: All Products fetched successfully
  productFetchErr: Failed to fetch all Products
  productSelect: Product Retrieved Successfully
  productSelectErr: Failed to retrieve Product
  productDelete: Product deleted successfully
  productDeleteErr: Failed to delete Products
  stockUpdate: Stock Updated Successfully
  stockUpdateErr: Failed to update stock
  loginErr: Invalid Credentials  
